In [1]:
from network_construction import NetworkConstruction
import pandas as pd
import pickle

In [2]:
path = '/home/gk/code/migration_project/'

In [3]:
vacancies = pd.read_csv(path + "vacancy_unique_cities.csv")
cv = pd.read_csv(path + "curricula_vitae_unique.csv")
responses = pd.read_csv(path + "responses.csv", sep=";")
cv_cities = pd.read_csv(path + "curricula_vitae_cities.csv")
cv_years = pd.read_csv(path + "curricula_vitae_years.csv")
kladr_2021 = pd.read_csv(path + "kladr.csv")
organizations = pd.read_csv(path + "organizations.csv", delimiter=";")

with open(path + "orgs_from_dadata_all.pkl", "rb") as f:
    org_cities = pickle.load(f)
org_cities = pd.DataFrame(org_cities)
org_cities = pd.json_normalize(org_cities.iloc[:, 0])

specialists = pd.read_csv('/home/gk/code/migration_project/specialists/specialists_table.csv')
ontology = pd.read_csv('/home/gk/Downloads/ontology.csv')
cv = pd.read_csv(path + "curricula_vitae_unique.csv")

/tmp/ipykernel_63284/2264843180.py:3: DtypeWarning: Columns (11) have mixed types. Specify dtype option on import or set low_memory=False.
  responses = pd.read_csv(path + "responses.csv", sep=";")
/tmp/ipykernel_63284/2264843180.py:7: DtypeWarning: Columns (36,37,38) have mixed types. Specify dtype option on import or set low_memory=False.
  organizations = pd.read_csv(path + "organizations.csv", delimiter=";")

In [26]:
ontology

,Отрасль,Уровень образования,Специальность,Код направления
0,Добыча нефти и газа,СПО,"Оператор, аппаратчик",21.01.05
1,Добыча нефти и газа,СПО,"Оператор, аппаратчик",21.01.16
2,Добыча нефти и газа,СПО,"Оператор, аппаратчик",21.02.18
3,Добыча нефти и газа,СПО,Монтажник,21.01.06
4,Добыча нефти и газа,СПО,Монтажник,21.01.14
...,...,...,...,...
246,Электроника и микроэлектроника,ВО,Инженер-конструктор,11.03.03
247,Электроника и микроэлектроника,ВО,Специалист по сертификации,27.03.01
248,Электроника и микроэлектроника,ВО,Технолог,11.03.04
249,Электроника и микроэлектроника,ВО,Технолог,11.03.03
250,Электроника и микроэлектроника,ВО,Инженер по качеству,27.03.02

In [27]:
G, responses2 = NetworkConstruction.run_pipeline(
    responses,
    vacancies,
    kladr_2021,
    organizations,
    org_cities,
    cv_years,
    cv_cities,
    cv,
    ontology,
    specialists,
    years=list(range(2018, 2022)),
    group=['Монтажник'],
    return_responses=True
)

/home/gk/code/migration_project/repo2/industrial-location/graph_calcs/network_construction.py:67: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  responses.loc[:, "year"] = responses["date_creation"].apply(
100%|██████████| 429/429 [00:00<00:00, 2902.25it/s]

In [28]:
responses2

,date_creation,id_candidate,id_cv,id_hiring_organization,id_response,id_vacancy,region_code,response_type,year,city_cv,x_cv,y_cv,city_vacancy,x_vacancy,y_vacancy,city,geo_lat,geo_lon
8376,2019-07-15,c12f2790-beb1-11e5-9eda-0163a9ae3d01,2ff598b0-9ce1-11e9-879d-e37b4be0b9ed,1136952017773,97f940c0-a6ef-11e9-845b-736ab11edb0c,eb00fcc6-42e3-11e8-9323-e37b4be0b9ed,7700000000000,Отказ,2019,Москва,55.755819,37.617644,Москва,55.751244,37.618423,Тверь,56.8462169,35.9042061
9313,2020-06-03,1e2649a0-8b7d-11ea-98d3-239861b1f67b,84497c10-8b7e-11ea-98d3-239861b1f67b,304662328800061,27496910-a584-11ea-bbd3-f3e0740405b3,05438ee2-996d-11ea-94f4-bf2cfe8c828d,6600000000000,Отказ,2020,Нижний Тагил,57.907562,59.971474,Нижний Тагил,57.91,59.96,NaN,NaN,NaN
10234,2021-10-07,82783890-24cb-11eb-83b1-25bddbcbae91,8a2efa80-f8d1-11eb-9288-69632329477c,1080273002325,2c519910-271e-11ec-bae9-0d5d229cdfdc,9edcbaa2-8d09-11eb-9dd6-bf2cfe8c828d,200000000000,Отказ,2021,Уфа,54.735152,55.958736,Уфа,54.77,56.24,NaN,NaN,NaN
10235,2021-09-15,82783890-24cb-11eb-83b1-25bddbcbae91,8a2efa80-f8d1-11eb-9288-69632329477c,319028000125728,0aea4140-1603-11ec-abbe-5d150a183f37,b0ded856-07a7-11ec-aded-ef1bf93dfa56,200000000000,Отказ,2021,Уфа,54.735152,55.958736,Уфа,54.77,56.04,NaN,NaN,NaN
10236,2021-09-15,82783890-24cb-11eb-83b1-25bddbcbae91,8a2efa80-f8d1-11eb-9288-69632329477c,1116189000036,1431be40-1603-11ec-abbe-5d150a183f37,8610fe42-a2e2-11e9-8ba1-bf2cfe8c828d,200000000000,Отказ,2021,Уфа,54.735152,55.958736,Уфа,54.8,56.13,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1331057,2020-06-09,c58a11b0-7c1c-11ea-80d4-736ab11edb0c,083eda60-a1b9-11ea-8a87-736ab11edb0c,8f62ab00-3a12-11e7-a1ca-ef76bd2a03c1,f000ae30-aa30-11ea-8876-037acc02728d,a9679506-0464-11ea-98aa-736ab11edb0c,3800000000000,Приглашение,2020,Иркутск,52.289588,104.280606,Иркутск,52.34,104.21,Москва,55.7680539,37.6520565
1331235,2018-08-27,eaad0560-b569-11e6-89c7-4376a32b3f45,143d4730-268b-11e8-b81e-037acc02728d,1172130006751,1edd2980-a9b7-11e8-9334-736ab11edb0c,3c003896-9635-11e7-9870-037acc02728d,2100000000000,Приглашение,2018,Алатырь,54.840526,46.591949,Ленинский район,56.1,47.24,NaN,NaN,NaN
1332806,2021-07-09,3e76c350-da33-11eb-9a39-a75f74b7b031,0fb420e0-da64-11eb-9cc3-c92c5fcfa4a0,36e48de0-f71a-11ea-aa3d-e736a3d3ed84,4725bfd0-e094-11eb-8250-3bfa22f2d66b,230ed752-d52a-11eb-9dd6-bf2cfe8c828d,5400000000000,Приглашение,2021,Лысьва,58.100417,57.811664,Новосибирск,55.0,82.86,NaN,NaN,NaN
1333645,2018-04-21,b7104000-62e0-11e5-9ba8-239645b044d5,34152340-e801-11e5-85ae-037acc02728d,5147746176001,bcc50200-452e-11e8-baf6-e37b4be0b9ed,01351646-bf98-11e7-808d-736ab11edb0c,7700000000000,Приглашение,2018,Верхний Уфалей,56.054673,60.221107,Москва,55.8,37.55,Москва,55.8480161,37.4277709
1334230,2020-08-04,143f4ef0-a400-11ea-a6c8-ef76bd2a03c1,7fa8fe90-a72d-11ea-a524-e736a3d3ed84,1127017019733,cf944870-d62f-11ea-aaeb-e736a3d3ed84,949bd806-d094-11ea-82f0-3bfa22f2d66b,7000000000000,Приглашение,2020,Томск,56.484645,84.947649,Томск,56.49,84.95,NaN,NaN,NaN

In [22]:
import numpy as np
np.sort(responses2.year.unique())

array([2015, 2016, 2017, 2018, 2019, 2020, 2021])